INSERT INTO street(street_name, region_id) VALUES ('проїзд 1-й Болгарський',3);
INSERT INTO street(street_name, region_id) VALUES ('провулок 1-й Варшавський',1);
INSERT INTO street(street_name, region_id) VALUES ('провулок 1-й Василя Сліпака',7);
INSERT INTO street(street_name, region_id) VALUES ('проїзд 1-й Гетьмана Мазепи',16);
INSERT INTO street(street_name, region_id) VALUES ('провулок 1-й Гната Танцюри',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок 1-й Ґданський',7);
INSERT INTO street(street_name, region_id) VALUES ('тупик 1-й Ґданський',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок 1-й Євгена Чикаленка',11);
INSERT INTO street(street_name, region_id) VALUES ('провулок 1-й Миколи Костомарова',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок 1-й Миколи Хвильового',11);
INSERT INTO street(street_name, region_id) VALUES ('провулок 1-й Мирослава Скорика',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок 1-й Олександра Лотоцького',12);
INSERT INTO street(street_name, region_id) VALUES ('провулок 1-й Олексія Миргородського',13);
INSERT INTO street(street_name, region_id) VALUES ('проїзд 1-й Олексія Миргородського',13);
INSERT INTO street(street_name, region_id) VALUES ('проїзд 1-й Праведників світу',11);
INSERT INTO street(street_name, region_id) VALUES ('провулок 1-й Романа Балаби',10);
INSERT INTO street(street_name, region_id) VALUES ('провулок 1-й Скіфський',13);
INSERT INTO street(street_name, region_id) VALUES ('провулок 1-й Софії Русової',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок 1-й Тетяни Яблонської',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок 2-й Болгарський',3);
INSERT INTO street(street_name, region_id) VALUES ('провулок 2-й Варшавський',1);
INSERT INTO street(street_name, region_id) VALUES ('провулок 2-й Василя Сліпака',7);
INSERT INTO street(street_name, region_id) VALUES ('проїзд 2-й Гетьмана Мазепи',16);
INSERT INTO street(street_name, region_id) VALUES ('провулок 2-й Гната Танцюри',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок 2-й Ґданський',7);
INSERT INTO street(street_name, region_id) VALUES ('тупик 2-й Ґданський',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок 2-й Євгена Чикаленка',11);
INSERT INTO street(street_name, region_id) VALUES ('провулок 2-й Миколи Костомарова',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок 2-й Миколи Хвильового',11);
INSERT INTO street(street_name, region_id) VALUES ('провулок 2-й Мирослава Скорика',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок 2-й Олександра Лотоцького',12);
INSERT INTO street(street_name, region_id) VALUES ('провулок 2-й Олексія Миргородського',13);
INSERT INTO street(street_name, region_id) VALUES ('проїзд 2-й Олексія Миргородського',13);
INSERT INTO street(street_name, region_id) VALUES ('проїзд 2-й Праведників світу',11);
INSERT INTO street(street_name, region_id) VALUES ('провулок 2-й Романа Балаби',10);
INSERT INTO street(street_name, region_id) VALUES ('провулок 2-й Скіфський',13);
INSERT INTO street(street_name, region_id) VALUES ('провулок 2-й Софії Русової',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок 2-й Тетяни Яблонської',7);
INSERT INTO street(street_name, region_id) VALUES ('проїзд 2-й Юрія Левади',13);
INSERT INTO street(street_name, region_id) VALUES ('провулок 3-й Варшавський',1);
INSERT INTO street(street_name, region_id) VALUES ('проїзд 3-й Гетьмана Мазепи',16);
INSERT INTO street(street_name, region_id) VALUES ('провулок 3-й Ґданський',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок 3-й Євгена Чикаленка',11);
INSERT INTO street(street_name, region_id) VALUES ('провулок 3-й Замковий',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок 3-й Олександра Лотоцького',12);
INSERT INTO street(street_name, region_id) VALUES ('проїзд 3-й Праведників світу',11);
INSERT INTO street(street_name, region_id) VALUES ('провулок 4-й Євгена Чикаленка',11);
INSERT INTO street(street_name, region_id) VALUES ('вулиця 20 Березня',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця 28 Червня',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця 600-річчя',2);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Агатангела Кримського',3);
INSERT INTO street(street_name, region_id) VALUES ('провулок Агатангела Кримського',3);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Аграрна',7);
INSERT INTO street(street_name, region_id) VALUES ('тупик Аграрний',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Айвазовського',10);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Академіка Вернадського',8);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Академіка Ющенка',4);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Академіка Янгеля',10);
INSERT INTO street(street_name, region_id) VALUES ('провулок Академіка Янгеля',10);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Академічна',17);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Анатолія Бортняка',4);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Анатолія Черниша',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Андрея Шептицького',17);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Андріївська',14);
INSERT INTO street(street_name, region_id) VALUES ('провулок Андріївський',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Андрія Первозванного',2);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Антона Листопада',11);
INSERT INTO street(street_name, region_id) VALUES ('провулок Антона Листопада',11);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Антона Турчановича',8);
INSERT INTO street(street_name, region_id) VALUES ('провулок Антона Турчановича 1-й',8);
INSERT INTO street(street_name, region_id) VALUES ('провулок Антона Турчановича 2-й',8);
INSERT INTO street(street_name, region_id) VALUES ('провулок Антона Турчановича 3-й',8);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Б. Лук''яновського',11);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Б. Хмельницького',10);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Барвиста',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок Барвистий',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Барське шосе',2);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Батозька',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Бевза',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Богдана Ступки',10);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Богомольця',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок Богомольця',7);
INSERT INTO street(street_name, region_id) VALUES ('тупик Богомольця',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Болгарська',3);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Ботанічна',11);
INSERT INTO street(street_name, region_id) VALUES ('проїзд Ботанічний',11);
INSERT INTO street(street_name, region_id) VALUES ('провулок Ботанічний 1-й',11);
INSERT INTO street(street_name, region_id) VALUES ('провулок Ботанічний 2-й',11);
INSERT INTO street(street_name, region_id) VALUES ('провулок Ботанічний 3-й',11);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Братів Котенків',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок Братів Котенків',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Брацлавська',1);
INSERT INTO street(street_name, region_id) VALUES ('провулок Брацлавський',1);
INSERT INTO street(street_name, region_id) VALUES ('тупик Брацлавський',1);
INSERT INTO street(street_name, region_id) VALUES ('проїзд Бузковий',8);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Бучми',8);
INSERT INTO street(street_name, region_id) VALUES ('провулок Бучми',8);
INSERT INTO street(street_name, region_id) VALUES ('вулиця В. Винниченка',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Валерія Лобановського',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Варшавська',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Василя Кричевського',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Василя Порика',2);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Василя Симоненка',12);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Василя Хмелюка',11);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Верхарна',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Володимира Антоновича',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Володимира Даценка',16);
INSERT INTO street(street_name, region_id) VALUES ('проїзд Володимира Даценка',16);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Володимира Свідзінського',12);
INSERT INTO street(street_name, region_id) VALUES ('провулок Володимира Свідзінського 1-й',12);
INSERT INTO street(street_name, region_id) VALUES ('провулок Володимира Свідзінського 2-й',12);
INSERT INTO street(street_name, region_id) VALUES ('провулок Володимира Свідзінського 3-й',12);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Волошкова',16);
INSERT INTO street(street_name, region_id) VALUES ('провулок Волошковий',16);
INSERT INTO street(street_name, region_id) VALUES ('проїзд Волошковий',16);
INSERT INTO street(street_name, region_id) VALUES ('вулиця вулиця Запорізька',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця вулиця Юрія Іллєнка',10);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Вячеслава Чорновола',10);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Генерала Арабея',11);
INSERT INTO street(street_name, region_id) VALUES ('проїзд Генерала Арабея 1-й',11);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Георгія Нарбута',10);
INSERT INTO street(street_name, region_id) VALUES ('провулок Георгія Нарбута',10);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Героїв Крут',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Героїв Нацгвардії',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Героїв поліції',3);
INSERT INTO street(street_name, region_id) VALUES ('площа Героїв Чорнобиля',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Гетьмана Мазепи',16);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Гетьмана Сагайдачного',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок Гетьмана Сагайдачного',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Гната Танцюри',7);
INSERT INTO street(street_name, region_id) VALUES ('тупик Гната Танцюри',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Гонти',10);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Ґданська',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Ґрохольських',11);
INSERT INTO street(street_name, region_id) VALUES ('провулок Ґрохольських',11);
INSERT INTO street(street_name, region_id) VALUES ('тупик Ґрохольських',11);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Данила Галицького',3);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Данила Нечая',7);
INSERT INTO street(street_name, region_id) VALUES ('проїзд Данила Нечая',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок Данила Нечая 1-й',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Деснянська',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Димчука',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Діонісія Міклера',12);
INSERT INTO street(street_name, region_id) VALUES ('провулок Діонісія Міклера',12);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Дмитра Майбороди',3);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Дубовецька',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Дьогтянецька',3);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Євгена Коновальця',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Євгена Чикаленка',11);
INSERT INTO street(street_name, region_id) VALUES ('провулок Євгена Чикаленка',11);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Євгенія Пікуса',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Заболотного',3);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Замкова',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Замостянська',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Захисників неба',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Зодчих',4);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Івана Богуна',12);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Івана Бойка',3);
INSERT INTO street(street_name, region_id) VALUES ('провулок Івана Бойка',3);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Івана Дзюби',3);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Івана Миколайчука',3);
INSERT INTO street(street_name, region_id) VALUES ('провулок Івана Миколайчука',3);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Івана Огієнка',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Івана Пулюя',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок Івана Пулюя',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Івана Федорова',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Івана-Павла ІІ',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Ігоря Костецького',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Казимира Малевича',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Келецька',2);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Київська',10);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Князів Коріатовичів',6);
INSERT INTO street(street_name, region_id) VALUES ('провулок Князів Коріатовичів',6);
INSERT INTO street(street_name, region_id) VALUES ('провулок Комарова',14);
INSERT INTO street(street_name, region_id) VALUES ('проспект Космонавтів',2);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Костя Широцького',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок Костя Широцького',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Костянтина Василенка',3);
INSERT INTO street(street_name, region_id) VALUES ('проспект Коцюбинського',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Л. Ратушної',3);
INSERT INTO street(street_name, region_id) VALUES ('провулок Л. Ратушної',3);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Лебединського',16);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Леоніда Каденюка',14);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Леонтовича',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Липовецька',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Лисенка',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Лівобережна',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок Лівобережний',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Максима Рильського',12);
INSERT INTO street(street_name, region_id) VALUES ('провулок Максима Рильського',12);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Максима Шимка',16);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Марії Гавриш',12);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Марії Литвиненко-Вольгемут',6);
INSERT INTO street(street_name, region_id) VALUES ('провулок 1-й Марії Литвиненко-Вольгемут ',6);
INSERT INTO street(street_name, region_id) VALUES ('тупик 1-й Марії Литвиненко-Вольгемут ',6);
INSERT INTO street(street_name, region_id) VALUES ('провулок Марії Литвиненко-Вольгемут 2-й',6);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Марії Приймаченко',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок Марії Приймаченко',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Маріупольська',7);
INSERT INTO street(street_name, region_id) VALUES ('провулок 1-й Маріупольський ',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Матроса Кішки',6);
INSERT INTO street(street_name, region_id) VALUES ('проїзд Медичний',12);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Медова',12);
INSERT INTO street(street_name, region_id) VALUES ('провулок Медовий',12);
INSERT INTO street(street_name, region_id) VALUES ('проїзд 1-й Медовий ',12);
INSERT INTO street(street_name, region_id) VALUES ('проїзд 2-й Медовий ',12);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Миколаївська',17);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Миколи Амосова',3);
INSERT INTO street(street_name, region_id) VALUES ('провулок Миколи Амосова',3);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Миколи Битинського',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Миколи Ващука',2);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Миколи Зерова',16);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Миколи Костомарова',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Миколи Куліша',10);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Миколи Стаховського',11);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Миколи Хвильового',11);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Мирослава Скорика',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Михайла Драгоманова',11);
INSERT INTO street(street_name, region_id) VALUES ('провулок Михайла Драгоманова',11);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Михайла Малишенка',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Могильчака',16);
INSERT INTO street(street_name, region_id) VALUES ('провулок Могильчака',16);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Можайського',10);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Монастирська',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Нагірна',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Нансена',1);
INSERT INTO street(street_name, region_id) VALUES ('провулок Наскрізний',3);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Насті Присяжнюк',10);
INSERT INTO street(street_name, region_id) VALUES ('тупик Насті Присяжнюк',10);
INSERT INTO street(street_name, region_id) VALUES ('провулок Насті Присяжнюк 1-й',8);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Натана Альтмана',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Немирівське шосе',16);
INSERT INTO street(street_name, region_id) VALUES ('провулок Немирівське шосе 1-й',16);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Нечуя-Левицького',10);
INSERT INTO street(street_name, region_id) VALUES ('вулиця О. Кобилянської',11);
INSERT INTO street(street_name, region_id) VALUES ('провулок О. Кобилянської',11);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Олега Антонова',16);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Олександра Божка',10);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Олександра Довженка',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Олександра Немченка',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Олександри Бурбело',3);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Омеляна Грабця',8);
INSERT INTO street(street_name, region_id) VALUES ('провулок 1-й Омеляна Грабця ',8);
INSERT INTO street(street_name, region_id) VALUES ('провулок 2-й Омеляна Грабця ',8);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Остапа Вишні',10);
INSERT INTO street(street_name, region_id) VALUES ('провулок Остапа Вишні',10);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Острозького',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Павла Корнелюка',10);
INSERT INTO street(street_name, region_id) VALUES ('проїзд Павла Корнелюка',10);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Павла Тичини',16);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Паліїв Яр',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Паневежиська',11);
INSERT INTO street(street_name, region_id) VALUES ('провулок Паневежиський',11);
INSERT INTO street(street_name, region_id) VALUES ('площа Перемоги',1);
INSERT INTO street(street_name, region_id) VALUES ('провулок Перемоги',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Привокзальна',1);
INSERT INTO street(street_name, region_id) VALUES ('площа Привокзальна',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Рєпіна',10);
INSERT INTO street(street_name, region_id) VALUES ('бульвар Свободи',4);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Стельмаха',2);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Стеценка',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Стрілецька',1);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Тараса Шевченка',3);
INSERT INTO street(street_name, region_id) VALUES ('площа Тараса Шевченка',3);
INSERT INTO street(street_name, region_id) VALUES ('проспект Юності',2);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Юрія Клена',16);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Якова Гальчевського',7);
INSERT INTO street(street_name, region_id) VALUES ('вулиця Якова Шепеля',7);
